# Generated by Django 4.1.2 on 2022-12-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurements',
            options={'verbose_name': ['measurement']},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'verbose_name': ['sensor']},
        ),
        migrations.AlterField(
            model_name='measurements',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
